[".linkerd2/bin/linkerd"]
  type = "file"
  url = "https://github.com/linkerd/linkerd2/releases/download/edge-{{ .tools.linkerd2.version }}/linkerd2-cli-edge-{{ .tools.linkerd2.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
[".linkerd2/bin/linkerd-smi"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "linkerd/linkerd-smi" (printf "linkerd-smi-*-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/bws"]
  type = "archive-file"
  path = "bws"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = 'https://github.com/bitwarden/sdk-sm/releases/download/bws-v{{ .tools.bws.version }}/bws-aarch64-apple-{{ .chezmoi.os }}-{{ .tools.bws.version }}.zip'
{{ else if eq .chezmoi.os "linux" -}}
  url = 'https://github.com/bitwarden/sdk-sm/releases/download/bws-v{{ .tools.bws.version }}/bws-x86_64-unknown-{{ .chezmoi.os }}-gnu-{{ .tools.bws.version }}.zip'
{{ end -}}
[".local/bin/hugo"]
  type = "archive-file"
  path = "hugo"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "gohugoio/hugo" (printf "hugo_*_*%s-universal.tar.gz" .chezmoi.os) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "gohugoio/hugo" (printf "hugo_extended_withdeploy_*%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
{{ end -}}
[".local/bin"]
  type = "archive"
  exact = false
  stripComponents = 1
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "nushell/nushell" (printf "nu-*-aarch64-apple-%s.tar.gz" .chezmoi.os) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "nushell/nushell" (printf "nu-*-x86_64-unknown-%s-gnu*" .chezmoi.os) }}'
{{ end -}}
[".local/bin/autok3s"]
  type = "file"
  executable = true
  url = '{{ gitHubLatestReleaseAssetURL "cnrancher/autok3s" (printf "autok3s_%s_%s*" .chezmoi.os .chezmoi.arch) }}'
[".local/bin/cloudflared"]
  type = "file"
  url = "https://github.com/cloudflare/cloudflared/releases/download/{{ .tools.cloudflared.version }}/cloudflared-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
[".local/bin/devspace"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "loft-sh/devspace" (printf "devspace-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/argocd"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "argoproj/argo-cd" (printf "argocd-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/kopia"]
  type = "archive-file"
  url = "https://github.com/kopia/kopia/releases/download/v{{ .tools.kopia.version }}/kopia-{{ .tools.kopia.version }}-{{ .chezmoi.os }}-x64.tar.gz"
  executable = true
  path = "kopia-{{ .tools.kopia.version }}-{{ .chezmoi.os }}-x64/kopia"
{{ end -}}
[".local/bin/git-credential-keepassxc"]
  type = "archive-file"
  path = "git-credential-keepassxc"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "Frederick888/git-credential-keepassxc" (printf "*macos*full*") }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "Frederick888/git-credential-keepassxc" (printf "*ubuntu*full*") }}'
{{ end -}}
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/jq"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "jqlang/jq" (printf "jq-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
{{ end -}}
[".local/bin/terraform"]
  type = "archive-file"
  url = "https://releases.hashicorp.com/terraform/{{ .tools.terraform.version }}/terraform_{{ .tools.terraform.version }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.zip"
  path = "terraform"
  executable = true
[".local/bin/terragrunt"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "gruntwork-io/terragrunt" (printf "terragrunt_%s_%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/bin/direnv"]
  type = "file"
  url = "https://github.com/direnv/direnv/releases/download/v{{ .tools.direnv.version }}/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
[".local/bin/kubectl"]
  type = "file"
  url = "https://dl.k8s.io/release/v{{ .tools.kubectl.version }}/bin/{{ .chezmoi.os }}/{{ .chezmoi.arch }}/kubectl"
  executable = true
[".local/bin/kubectl-oidc_login"]
  type = "archive-file"
  url = '{{ gitHubLatestReleaseAssetURL "int128/kubelogin" (printf "kubelogin_%s_%s.zip" .chezmoi.os .chezmoi.arch) }}'
  executable = true
  path = "kubelogin"
[".local/bin/k3d"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "k3d-io/k3d" (printf "k3d-%s-%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/bin/kind"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "kubernetes-sigs/kind" (printf "kind-%s-%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/bin/k9s"]
  type = "archive-file"
  executable = true
  path = "k9s"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "derailed/k9s" (printf "k9s_Darwin_%s*.tar.gz" .chezmoi.arch) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "derailed/k9s" (printf "k9s_Linux_%s*.tar.gz" .chezmoi.arch) }}'
{{ end -}}
[".local/bin/age"]
  type = "archive-file"
  url = "https://github.com/FiloSottile/age/releases/download/v{{ .tools.age.version }}/age-v{{ .tools.age.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  path = "age/age"
  executable = true
[".local/bin/sops"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "getsops/sops" (printf "sops-*.%s.%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/vcluster"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "loft-sh/vcluster" (printf "vcluster-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/task"]
  type = "archive-file"
  url = "https://github.com/go-task/task/releases/download/v{{ .tools.go_task.version }}/task_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
  path = "task"
  executable = true
[".local/bin/yq"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "mikefarah/yq" (printf "yq_%s_%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/vagrant"]
  type = "archive-file"
  url = "https://releases.hashicorp.com/vagrant/{{ .tools.vagrant.version }}/vagrant_{{ .tools.vagrant.version }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.zip"
  path = "vagrant"
  executable = true
[".local/bin/rclone"]
  type = "archive-file"
  url = "https://downloads.rclone.org/v{{ .tools.rclone.version }}/rclone-v{{ .tools.rclone.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.zip"
  path = "rclone-v{{ .tools.rclone.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}/rclone"
  executable = true
{{ end -}}
[".local/bin/docker-compose"]
  type = "file"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "docker/compose" (printf "docker-compose-%s-aarch64*" .chezmoi.os ) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "docker/compose" (printf "docker-compose-%s-x86_64*" .chezmoi.os ) }}'
{{ end -}}
[".local/bin/zoxide"]
  type = "archive-file"
  executable = true
  path = "zoxide"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "ajeetdsouza/zoxide" (printf "*aarch64-apple-%s.tar.gz" .chezmoi.os) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "ajeetdsouza/zoxide" (printf "*x86_64-unknown-%s-musl*" .chezmoi.os) }}'
{{ end -}}
[".local/bin/helm"]
  type = "archive-file"
  url = "https://get.helm.sh/helm-v{{ .tools.helm.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable = true
  path = "{{ .chezmoi.os }}-{{ .chezmoi.arch }}/helm"
[".local/bin/lazygit"]
  type = "archive-file"
  executable = true
  path = "lazygit"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" (printf "*darwin_x86_64*" ) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" (printf "*linux_x86_64*" ) }}'
{{ end -}}

[".local/bin/flux"]
  type = "archive-file"
  url = "https://github.com/fluxcd/flux2/releases/download/v{{ .tools.flux.version }}/flux_{{ .tools.flux.version }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
  path = "flux"
  executable = true
[".local/bin/bat"]
  type = "archive-file"
  {{ $batVersion := (gitHubLatestRelease "sharkdp/bat").TagName }}
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "sharkdp/bat" (printf "*aarch64-apple-%s*" .chezmoi.os ) }}'
  path = "bat-{{ $batVersion }}-aarch64-apple-{{ .chezmoi.os }}/bat"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "sharkdp/bat" (printf "*x86_64-unknown-%s-gnu*" .chezmoi.os ) }}'
  path = "bat-{{ $batVersion }}-x86_64-unknown-{{ .chezmoi.os }}-gnu/bat"
{{ end -}}
[".local/bin/fzf"]
  type = "archive-file"
  url = '{{ gitHubLatestReleaseAssetURL "junegunn/fzf" (printf "*%s_%s*" .chezmoi.os .chezmoi.arch) }}'
  path = "fzf"
[".local/bin/fd"]
  type = "archive-file"
  {{ $fdVersion := (gitHubLatestRelease "sharkdp/fd").TagName }}
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "sharkdp/fd" (printf "fd-*-aarch64-apple-%s*" .chezmoi.os) }}'
  path = "fd-{{ $fdVersion }}-aarch64-apple-{{ .chezmoi.os }}/fd"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "sharkdp/fd" (printf "fd-*-x86_64-unknown-%s-gnu*" .chezmoi.os) }}'
  path = "fd-{{ $fdVersion }}-x86_64-unknown-{{ .chezmoi.os }}-gnu/fd"
{{ end -}}
[".local/bin/rg"]
  type = "archive-file"
  {{ $rgVersion := (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" (printf "*-aarch64-apple-%s*" .chezmoi.os ) }}'
  path = "ripgrep-{{ $rgVersion }}-aarch64-apple-{{ .chezmoi.os }}/rg"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" (printf "*x86_64-unknown-%s-musl*" .chezmoi.os ) }}'
  path = "ripgrep-{{ $rgVersion }}-x86_64-unknown-{{ .chezmoi.os }}-musl/rg"
{{ end -}}
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/speedtest"]
  type = "archive-file"
  url = "https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz"
  path = "speedtest"
  executable = true
[".local/bin/eza"]
  type = "archive-file"
  url = '{{ gitHubLatestReleaseAssetURL "eza-community/eza" (printf "eza_x86_64-unknown-%s-gnu.zip" .chezmoi.os) }}'
  path = "eza"
  executable = true
{{ end -}}
[".tmux.conf"]
  type = "file"
  url = 'https://raw.githubusercontent.com/gpakosz/.tmux/refs/heads/master/.tmux.conf'
{{ if eq .chezmoi.os "linux" -}}
[".local/share/fonts"]
  type = "archive"
  url = '{{ gitHubLatestReleaseAssetURL "adobe-fonts/source-code-pro" (printf "OTF-source-code-pro-*.zip") }}'
  exact = false
  stripComponents = 1
{{ end -}}
[".local/"]
  type = "archive"
  exact = false
  stripComponents = 1
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "neovim/neovim" (printf "nvim-macos-*%s.tar.gz" .chezmoi.arch) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "neovim/neovim" (printf "nvim-*%s-x86_64.tar.gz" .chezmoi.os) }}'
{{ end -}}
# curl -LsSf https://astral.sh/uv/install.sh | sh
[".local/bin/uv"]
  type = "archive-file"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-aarch64-apple-%s.tar.gz" .chezmoi.os) }}'
  path = "uv-aarch64-apple-{{ .chezmoi.os }}/uv"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-x86_64-unknown-%s-gnu.tar.gz" .chezmoi.os) }}'
  path = "uv-x86_64-unknown-{{ .chezmoi.os }}-gnu/uv"
{{ end -}}
[".local/bin/uvx"]
  type = "archive-file"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-aarch64-apple-%s.tar.gz" .chezmoi.os) }}'
  path = "uv-aarch64-apple-{{ .chezmoi.os }}/uvx"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-x86_64-unknown-%s-gnu.tar.gz" .chezmoi.os) }}'
  path = "uv-x86_64-unknown-{{ .chezmoi.os }}-gnu/uvx"
{{ end -}}
[".local/go"]
  type = "archive"
  url = "https://go.dev/dl/go{{ .tools.go.version }}.{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  exact = false
  stripComponents = 1

[".local/bin/operator-sdk"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "operator-framework/operator-sdk" (printf "operator-sdk_%s_%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/bin/helm-operator"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "operator-framework/operator-sdk" (printf "helm-operator_%s_%s*" .chezmoi.os .chezmoi.arch) }}'
  executable = true
[".local/google-cloud-sdk"]
  type = "archive"
  exact = false
  stripComponents = 1
{{ if eq .chezmoi.os "darwin" -}}
  url = "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-darwin-arm.tar.gz"
{{ else if eq .chezmoi.os "linux" -}}
  url = "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz"
{{ end -}}
[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv.git"
[".local/bin/k6"]
  type = "archive-file"
  executable = true
{{ $k6sVersion := (gitHubLatestRelease "grafana/k6").TagName }}
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "grafana/k6" (printf "k6-*-macos-%s.zip" .chezmoi.arch) }}'
  path = "k6-{{ $k6sVersion }}-macos-{{ .chezmoi.arch }}/k6"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "grafana/k6" (printf "k6-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
  path = "k6-{{ $k6sVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}/k6"
{{ end -}}
[".local/bin/kubectl-krew"]
  type = "archive-file"
  executable = true
  url = '{{ gitHubLatestReleaseAssetURL "kubernetes-sigs/krew" (printf "krew-%s_%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
  path = "./krew-{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
[".local/bin/minikube"]
  type = "file"
  executable = true
  url = '{{ gitHubLatestReleaseAssetURL "kubernetes/minikube" (printf "minikube-%s-%s" .chezmoi.os .chezmoi.arch) }}'

[".local/bin/croc"]
  type = "archive-file"
  executable = true
  path = "croc"
{{ if eq .chezmoi.os "darwin" -}}
  url = {{ gitHubLatestReleaseAssetURL "schollz/croc" "croc_v*_macOS-ARM64.tar.gz" | quote }}
{{ else if eq .chezmoi.os "linux" -}}
  url = {{ gitHubLatestReleaseAssetURL "schollz/croc" "croc_v*_Linux-64bit.tar.gz" | quote }}
{{ end -}}
[".local/bin/glow"]
    type = "archive-file"
    executable = true
    stripComponents = 1
    path = "glow"
{{ if eq .chezmoi.os "darwin" -}}
    url = {{ gitHubLatestReleaseAssetURL "charmbracelet/glow" "glow_*_Darwin_arm64.tar.gz" | quote }}
{{ else if eq .chezmoi.os "linux" -}}
    url = {{ gitHubLatestReleaseAssetURL "charmbracelet/glow" "glow_*_Linux_x86_64.tar.gz" | quote }}
{{ end -}}
[".local/bin/vault"]
  type = "archive-file"
  executable = true
{{ $vaultVersionRaw := (gitHubLatestRelease "hashicorp/vault").TagName }}
{{ $vaultVersion := trimPrefix "v" $vaultVersionRaw }}
  url = 'https://releases.hashicorp.com/vault/{{ $vaultVersion }}/vault_{{ $vaultVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.zip'
  path = "vault"

# ex: ts=4 sw=4 et filetype=toml
