[".local/bin/jq"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "jqlang/jq" (printf "jq-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/direnv"]
  type = "file"
  url = "https://github.com/direnv/direnv/releases/download/v{{ .tools.direnv.version }}/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
[".local/bin/kubectl"]
  type = "file"
  url = "https://dl.k8s.io/release/v{{ .tools.kubectl.version }}/bin/{{ .chezmoi.os }}/{{ .chezmoi.arch }}/kubectl"
  executable = true
[".local/bin/kubectl-oidc_login"]
  type = "archive-file"
  url = '{{ gitHubLatestReleaseAssetURL "int128/kubelogin" (printf "kubelogin_%s_%s.zip" .chezmoi.os .chezmoi.arch) }}'
  executable = true
  path = "kubelogin"
[".local/bin/k9s"]
  type = "archive-file"
  executable = true
  path = "k9s"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "derailed/k9s" (printf "k9s_Darwin_%s*.tar.gz" .chezmoi.arch) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "derailed/k9s" (printf "k9s_Linux_%s*.tar.gz" .chezmoi.arch) }}'
{{ end -}}
[".local/bin/age"]
  type = "archive-file"
  url = "https://github.com/FiloSottile/age/releases/download/v{{ .tools.age.version }}/age-v{{ .tools.age.version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  path = "age/age"
  executable = true
[".local/bin/sops"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "getsops/sops" (printf "sops-*.%s.%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/vcluster"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "loft-sh/vcluster" (printf "vcluster-%s-%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/yq"]
  type = "file"
  url = '{{ gitHubLatestReleaseAssetURL "mikefarah/yq" (printf "yq_%s_%s*" .chezmoi.os .chezmoi.arch ) }}'
  executable = true
[".local/bin/docker-compose"]
  type = "file"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "docker/compose" (printf "docker-compose-%s-aarch64*" .chezmoi.os ) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "docker/compose" (printf "docker-compose-%s-x86_64*" .chezmoi.os ) }}'
{{ end -}}
[".local/bin/lazygit"]
  type = "archive-file"
  executable = true
  path = "lazygit"
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" (printf "*darwin_x86_64*" ) }}'
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" (printf "*linux_x86_64*" ) }}'
{{ end -}}
[".tmux.conf"]
  type = "file"
  url = 'https://raw.githubusercontent.com/gpakosz/.tmux/refs/heads/master/.tmux.conf'
# curl -LsSf https://astral.sh/uv/install.sh | sh
[".local/bin/uv"]
  type = "archive-file"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-aarch64-apple-%s.tar.gz" .chezmoi.os) }}'
  path = "uv-aarch64-apple-{{ .chezmoi.os }}/uv"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-x86_64-unknown-%s-gnu.tar.gz" .chezmoi.os) }}'
  path = "uv-x86_64-unknown-{{ .chezmoi.os }}-gnu/uv"
{{ end -}}
[".local/bin/uvx"]
  type = "archive-file"
  executable = true
{{ if eq .chezmoi.os "darwin" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-aarch64-apple-%s.tar.gz" .chezmoi.os) }}'
  path = "uv-aarch64-apple-{{ .chezmoi.os }}/uvx"
{{ else if eq .chezmoi.os "linux" -}}
  url = '{{ gitHubLatestReleaseAssetURL "astral-sh/uv" (printf "uv-x86_64-unknown-%s-gnu.tar.gz" .chezmoi.os) }}'
  path = "uv-x86_64-unknown-{{ .chezmoi.os }}-gnu/uvx"
{{ end -}}
[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv.git"
# ex: ts=4 sw=4 et filetype=toml
